# Generated by Django 4.2.6 on 2023-10-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_conteudo_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontuacao',
            name='exercicio',
        ),
    ]
