# Generated by Django 4.2.6 on 2023-11-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_pontuacao_exercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='descricao',
            field=models.TextField(),
        ),
    ]
