# Generated by Django 4.2.6 on 2023-11-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_conteudo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumoatividade',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
