# Generated by Django 4.2.6 on 2023-11-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_resumoatividade_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='imagem',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
