# Generated by Django 4.2.6 on 2023-11-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_exercicio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='enunciado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='imagem',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
