# Generated by Django 4.2.6 on 2023-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_exercicio_enunciado_alter_exercicio_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='imagem',
            field=models.FileField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
