# Generated by Django 4.2.6 on 2023-11-20 11:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_conteudo_imagem_alter_conteudo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='imagem',
            field=models.FileField(blank=True, upload_to=app.models.gerar_nome_aleatorio),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='imagem',
            field=models.FileField(blank=True, upload_to=app.models.gerar_nome_aleatorio),
        ),
    ]
